name: Node.js CI

on: [push]

jobs:
  test-server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        working-directory: ./server
        run: npm i
      - name: Run tests
        working-directory: ./server
        run: npm test
  build-reporter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        working-directory: ./reporter
        run: npm i
      - name: Compile
        working-directory: ./reporter
        run: npm run build
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Go to release branch
        run: git checkout -B $(node -p -e "require('./package.json').version")
      - name: Merge with master
        run: git merge origin/master --no-edit
      - name: Authenticate with GitHub package registry to be able to download from private repositories
        run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" > ~/.npmrc
      - name: npm install
        working-directory: ./reporter
        run: npm i
      - name: run build
        working-directory: ./reporter
        run: npm run build
      - name: add and push
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git add -A
          git commit -m "Compiled new reporter version"
          git push --force https://$GITHUB_ACTOR:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY $(node -p -e "require('./package.json').version")
