name: Node.js CI

on: [push]

jobs:
  Test Server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        working-directory: ./server
        run: npm i
      - name: Run tests
        working-directory: ./server
        run: npm test
